//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaio.CompositeC1Packages.IssuuDocument.Package.Composite.InstalledPackages.IssuuDocument {
    
    
    public partial class IssuuDocumentConfig {
        
        /// <summary>
        /// Form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm Form1;
        
        /// <summary>
        /// ApiKey control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
		protected global::Composite.Plugins.Forms.WebChannel.UiControlFactories.TextInputTemplateUserControlBase ApiKey;
        
        /// <summary>
        /// ApiSecretKey control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
		protected global::Composite.Plugins.Forms.WebChannel.UiControlFactories.TextInputTemplateUserControlBase ApiSecretKey;
        
        /// <summary>
        /// ApiUrl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
		protected global::Composite.Plugins.Forms.WebChannel.UiControlFactories.TextInputTemplateUserControlBase ApiUrl;
        
        /// <summary>
        /// RequestsPerSec control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
		protected global::Composite.Plugins.Forms.WebChannel.UiControlFactories.TextInputTemplateUserControlBase RequestsPerSec;
    }
}
