//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garaio.CompositeC1Packages.IssuuDocument.Package.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Garaio.CompositeC1Packages.IssuuDocument.Package.App_GlobalResources.Resources.Te" +
                            "xt", typeof(Resources_Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API-Key.
        /// </summary>
        public static string IssuuDocument_Configuration_APIKey_Label {
            get {
                return ResourceManager.GetString("IssuuDocument_Configuration_APIKey_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API-Secret Key.
        /// </summary>
        public static string IssuuDocument_Configuration_APISecretKey_Label {
            get {
                return ResourceManager.GetString("IssuuDocument_Configuration_APISecretKey_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API-URL.
        /// </summary>
        public static string IssuuDocument_Configuration_APIURL_Label {
            get {
                return ResourceManager.GetString("IssuuDocument_Configuration_APIURL_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuu Settings.
        /// </summary>
        public static string IssuuDocument_Configuration_Label {
            get {
                return ResourceManager.GetString("IssuuDocument_Configuration_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of requests per second (http://developers.issuu.com/api/limits.html).
        /// </summary>
        public static string IssuuDocument_Configuration_RequestsPerSec_Label {
            get {
                return ResourceManager.GetString("IssuuDocument_Configuration_RequestsPerSec_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        public static string IssuuDocument_Configuration_SaveButton_Label {
            get {
                return ResourceManager.GetString("IssuuDocument_Configuration_SaveButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrate an Issuu Document from Issuu.com..
        /// </summary>
        public static string IssuuDocument_FunctionDescription {
            get {
                return ResourceManager.GetString("IssuuDocument_FunctionDescription", resourceCulture);
            }
        }
    }
}
