//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class IssuuDocumentConfiguration {
    
    private string nameField;
    
    private string aPIKeyField;
    
    private string aPISecretKeyField;
    
    private string aPIUrlField;
    
    private string requestsProSecondField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string APIKey {
        get {
            return this.aPIKeyField;
        }
        set {
            this.aPIKeyField = value;
        }
    }
    
    /// <remarks/>
    public string APISecretKey {
        get {
            return this.aPISecretKeyField;
        }
        set {
            this.aPISecretKeyField = value;
        }
    }
    
    /// <remarks/>
    public string APIUrl {
        get {
            return this.aPIUrlField;
        }
        set {
            this.aPIUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string RequestsProSecond {
        get {
            return this.requestsProSecondField;
        }
        set {
            this.requestsProSecondField = value;
        }
    }
}
