//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.TextResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API-Key.
        /// </summary>
        internal static string IssuuDocument_Configuration_APIKey_Label {
            get {
                return ResourceManager.GetString("IssuuDocument_Configuration_APIKey_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API-Secret Key.
        /// </summary>
        internal static string IssuuDocument_Configuration_APISecretKey_Label {
            get {
                return ResourceManager.GetString("IssuuDocument_Configuration_APISecretKey_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API-URL.
        /// </summary>
        internal static string IssuuDocument_Configuration_APIURL_Label {
            get {
                return ResourceManager.GetString("IssuuDocument_Configuration_APIURL_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuu Settings.
        /// </summary>
        internal static string IssuuDocument_Configuration_Label {
            get {
                return ResourceManager.GetString("IssuuDocument_Configuration_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of requests per second (http://developers.issuu.com/api/limits.html).
        /// </summary>
        internal static string IssuuDocument_Configuration_RequestsPerSec_Label {
            get {
                return ResourceManager.GetString("IssuuDocument_Configuration_RequestsPerSec_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        internal static string IssuuDocument_Configuration_SaveButton_Label {
            get {
                return ResourceManager.GetString("IssuuDocument_Configuration_SaveButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integrate an Issuu Document from Issuu.com..
        /// </summary>
        internal static string IssuuDocument_FunctionDescription {
            get {
                return ResourceManager.GetString("IssuuDocument_FunctionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string IssuuDocument_FunctionParameter_Height {
            get {
                return ResourceManager.GetString("IssuuDocument_FunctionParameter_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The height of the Issuu-Element..
        /// </summary>
        internal static string IssuuDocument_FunctionParameter_HeightHelp {
            get {
                return ResourceManager.GetString("IssuuDocument_FunctionParameter_HeightHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string IssuuDocument_FunctionParameter_SelectedDataConfigId {
            get {
                return ResourceManager.GetString("IssuuDocument_FunctionParameter_SelectedDataConfigId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Document to display. List contains available Documents received from the Issuu-Service.
        /// </summary>
        internal static string IssuuDocument_FunctionParameter_SelectedDataConfigIdHelp {
            get {
                return ResourceManager.GetString("IssuuDocument_FunctionParameter_SelectedDataConfigIdHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string IssuuDocument_FunctionParameter_Width {
            get {
                return ResourceManager.GetString("IssuuDocument_FunctionParameter_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The width of the Issuu-Element..
        /// </summary>
        internal static string IssuuDocument_FunctionParameter_WidthHelp {
            get {
                return ResourceManager.GetString("IssuuDocument_FunctionParameter_WidthHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issuu Konfiguration Manager starten.
        /// </summary>
        internal static string IssuuDocument_Tree_ActionLabel {
            get {
                return ResourceManager.GetString("IssuuDocument_Tree_ActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager zum konfigurieren des Issuu-Kontos..
        /// </summary>
        internal static string IssuuDocument_Tree_ActionToolTip {
            get {
                return ResourceManager.GetString("IssuuDocument_Tree_ActionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IssuuDocument Konfiguration.
        /// </summary>
        internal static string IssuuDocument_Tree_Label {
            get {
                return ResourceManager.GetString("IssuuDocument_Tree_Label", resourceCulture);
            }
        }
    }
}
